### ISSUE TITLE
Multiple command example is incorrect

### ISSUE THREAD

**Issue by marcopelegrini** [qoomon/zsh-lazyload#1]
Current:
`lazyload <command-name, command-name, ...> -- <load-command>`

Fixed:
`lazyload <command-name command-name2 ...> -- <load-command>`
(should not be comma separated)

**Comment by qoomon** [comment]
you are right, I will fix it right away. thank you

**Comment by marcopelegrini** [comment]
Thanks for the good work. Great tool

**Comment by qoomon** [comment]
Thx, glad to hear that.
